name: Daily Spotify Shuffle

on:
  schedule:
    # Runs every day at 06:00 UTC (adjust as desired)
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      playlist_id:
        description: "Playlist ID to shuffle (optional; falls back to variable PLAYLIST_ID)"
        required: false
        type: string

permissions:
  contents: read

concurrency:
  group: daily-shuffle
  cancel-in-progress: false

jobs:
  shuffle:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      CLIENT_ID: ${{ vars.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDIRECT_URI: ${{ vars.REDIRECT_URI }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      # Prefer passing playlist via workflow input; otherwise use variable PLAYLIST_ID
      PLAYLIST_ID: ${{ inputs.playlist_id || vars.PLAYLIST_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run shuffle
        id: run
        env:
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
          REDIRECT_URI: ${{ env.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ env.REFRESH_TOKEN }}
          PLAYLIST_ID: ${{ env.PLAYLIST_ID }}
        run: uv run python spotify_api/spotify_client.py --shuffle ${PLAYLIST_ID}